### ISSUE TITLE
Асинх и Ждать

### ISSUE THREAD

**Issue by CrazyHackGUT** [zeegin/pygments-bsl#8]
В версии платформы 8.3.18 добавили поддержку "асинхронной синхронности". Будет ли поддержка новых ключевых слов (Асинх, Ждать) и нового класса (Обещание) здесь?
[Заметка на Зазеркалье](https://wonderland.v8.1c.ru/blog/uluchsheniya-v-sintaksise-yazyka-1s-dlya-raboty-s-asinkhronnymi-funktsiyami/)

**Comment by zeegin** [comment]
Да, это поддержать легко.

**Comment by zeegin** [comment]
Выпущено в версии [v0.10.0](https://github.com/zeegin/pygments-bsl/tree/v0.10.0)
